/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;
import calculadora.Logica;
/**
 *
 * @author Estudiante
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        limpiar = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_restar = new javax.swing.JButton();
        btn_sumar = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        txt_resultado = new javax.swing.JLabel();
        btn_dividir = new javax.swing.JButton();
        img_resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_resultado1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/Calculadora (5).png"))); // NOI18N
        jLabel11.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 102, 102));
        exit.setBorder(new javax.swing.border.MatteBorder(null));
        exit.setOpaque(true);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 20, 20));

        jPanel1.setBackground(new java.awt.Color(54, 89, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        limpiar.setBackground(new java.awt.Color(54, 89, 129));
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB.png"))); // NOI18N
        limpiar.setBorder(null);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, 60));

        btn_2.setBackground(new java.awt.Color(54, 89, 129));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-13.png"))); // NOI18N
        btn_2.setBorder(null);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 60));

        btn_6.setBackground(new java.awt.Color(54, 89, 129));
        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-10.png"))); // NOI18N
        btn_6.setBorder(null);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 60, 60));

        btn_8.setBackground(new java.awt.Color(54, 89, 129));
        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-8.png"))); // NOI18N
        btn_8.setBorder(null);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 60));

        btn_1.setBackground(new java.awt.Color(54, 89, 129));
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-6.png"))); // NOI18N
        btn_1.setBorder(null);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 60));

        btn_0.setBackground(new java.awt.Color(54, 89, 129));
        btn_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-5.png"))); // NOI18N
        btn_0.setBorder(null);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 60, 60));

        btn_igual.setBackground(new java.awt.Color(54, 89, 129));
        btn_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-3.png"))); // NOI18N
        btn_igual.setBorder(null);
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel1.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 60, 60));

        btn_restar.setBackground(new java.awt.Color(54, 89, 129));
        btn_restar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-1.png"))); // NOI18N
        btn_restar.setBorder(null);
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, 60));

        btn_sumar.setBackground(new java.awt.Color(54, 89, 129));
        btn_sumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-2.png"))); // NOI18N
        btn_sumar.setBorder(null);
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, 60));

        btn_7.setBackground(new java.awt.Color(54, 89, 129));
        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-12.png"))); // NOI18N
        btn_7.setBorder(null);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 60));

        btn_3.setBackground(new java.awt.Color(54, 89, 129));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-14.png"))); // NOI18N
        btn_3.setBorder(null);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, 60));

        btn_9.setBackground(new java.awt.Color(54, 89, 129));
        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-7.png"))); // NOI18N
        btn_9.setBorder(null);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 60, 60));

        btn_multiplicar.setBackground(new java.awt.Color(54, 89, 129));
        btn_multiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-4.png"))); // NOI18N
        btn_multiplicar.setBorder(null);
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 60, 60));

        btn_5.setBackground(new java.awt.Color(54, 89, 129));
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-9.png"))); // NOI18N
        btn_5.setBorder(null);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 60));

        btn_4.setBackground(new java.awt.Color(54, 89, 129));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-11.png"))); // NOI18N
        btn_4.setBorder(null);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, 60));

        txt_resultado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_resultado.setText("000");
        jPanel1.add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 30));

        btn_dividir.setBackground(new java.awt.Color(54, 89, 129));
        btn_dividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Extended FAB-15.png"))); // NOI18N
        btn_dividir.setBorder(null);
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 60));

        img_resultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        img_resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Text field.png"))); // NOI18N
        img_resultado.setToolTipText("");
        jPanel1.add(img_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/Calculadora (5).png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 330));

        txt_resultado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_resultado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Text field.png"))); // NOI18N
        txt_resultado1.setToolTipText("");
        getContentPane().add(txt_resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String memory;
    
    int operacion;
    private static final int SUMA = 0;
    private static final int RESTA = 1;
    private static final int MULTIPLICACION = 2;
    private static final int DIVISION = 3;
    String numBack;
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        txt_resultado.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        txt_resultado.setText("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        Logica log = new Logica(memory, txt_resultado.getText(), operacion);
        txt_resultado.setText(log.getResultado()+ "");
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        almacenarMemoria(RESTA);
    }//GEN-LAST:event_btn_restarActionPerformed

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        almacenarMemoria(SUMA);
    }//GEN-LAST:event_btn_sumarActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        almacenarMemoria(MULTIPLICACION);
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        numBack = txt_resultado.getText();
        txt_resultado.setText(numBack + "4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        almacenarMemoria(DIVISION); 
    }//GEN-LAST:event_btn_dividirActionPerformed
    private void almacenarMemoria(int ope){
        memory = txt_resultado.getText();
        txt_resultado.setText("");
        operacion = ope;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JButton exit;
    private javax.swing.JLabel img_resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel txt_resultado;
    private javax.swing.JLabel txt_resultado1;
    // End of variables declaration//GEN-END:variables
}
